name: code-coverage-action
on: [push]

jobs:
  run_hardhat_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    name: A job to run code coverage

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install node modules
        run: npm install
      - name: Run testing
        run: npm run test:coverage
