name: 'PR'
on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git branch --track ${{ github.base_ref }} origin/${{ github.base_ref }}
      - name: Install
        uses: ./.github/actions/prepare-install
      - name: Build
        uses: ./.github/actions/prepare-build
        with:
          cache-key: ${{ github.event.number }}
      - run: yarn run format
      - name: Check format
        run: |
          if [ -z "$(git status --untracked-files=no --porcelain)" ]; then
            echo "All files formatted"
          else
            echo "Running format is required"
            exit 1
          fi
      - run: yarn run lint

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        uses: ./.github/actions/prepare-install
      - name: Build
        uses: ./.github/actions/prepare-build
        with:
          cache-key: ${{ github.event.number }}

  unit-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        uses: ./.github/actions/prepare-install
      - name: Build
        uses: ./.github/actions/prepare-build
        with:
          cache-key: ${{ github.event.number }}
      - run: yarn test
